#!/usr/bin/env python3
# contour_golden.py
# Generates: heightmap.hex, golden_p0.txt (default rainbow), golden_p1.txt
# (cividis), and palettes.svh (SV localparams P0/P1/P2 for the loader ROM).
# Bit-exact with contour_unit.sv: same scaling constants, same band index.

import math
import matplotlib.cm as cm

W, H = 640, 480
GRID_N = 64
H_W, H_I = 16, 2
H_F = H_W - 1 - H_I
SH, RX, RY = 14, 1639, 2185

# P0: default rainbow (MUST match DEFAULT_PAL in contour_unit.sv)
P0 = [
    (0,0,255),(0,80,255),(0,160,255),(0,255,255),
    (0,255,160),(0,255,80),(0,255,0),(128,255,0),
    (200,255,0),(255,255,0),(255,200,0),(255,160,0),
    (255,100,0),(255,40,0),(255,0,0),(180,0,0),
]

def sample_cmap(name, n=16):
    m = cm.get_cmap(name)
    out = []
    for i in range(n):
        r,g,b,_ = m(i/(n-1))
        out.append((round(r*255), round(g*255), round(b*255)))
    return out

P1 = sample_cmap("cividis")   # deuteranopia-optimised, monotonic luminance
P2 = sample_cmap("viridis")   # CVD-safe, monotonic luminance

def to_q(x):
    v = int(round(x * (1 << H_F)))
    lo, hi = -(1 << (H_W-1)), (1 << (H_W-1)) - 1
    return (max(lo, min(hi, v))) & 0xFFFF

def make_heightmap():
    mem = [0]*(GRID_N*GRID_N)
    for iy in range(GRID_N):
        for ix in range(GRID_N):
            u, v = ix/(GRID_N-1), iy/(GRID_N-1)
            z  = 2.5*math.exp(-(((u-0.30)**2+(v-0.65)**2)/0.05))
            z -= 2.0*math.exp(-(((u-0.70)**2+(v-0.30)**2)/0.04))
            z += 1.2*math.sin(3.1*u)*math.cos(2.7*v)
            z += 1.5*(u-0.5)
            mem[iy*GRID_N+ix] = to_q(z)
    return mem

def scale_idx(p, recip):
    raw = (p*recip) >> SH
    return GRID_N-1 if raw >= GRID_N else raw

def band_of(h16):
    return ((h16 ^ 0x8000) >> 12) & 0xF

def write_golden(fname, mem, pal):
    with open(fname, "w") as f:
        for py in range(H):
            iy = scale_idx(py, RY)
            for px in range(W):
                ix = scale_idx(px, RX)
                r,g,b = pal[band_of(mem[iy*GRID_N+ix])]
                f.write(f"{px} {py} {r} {g} {b}\n")

def emit_svh(palettes):
    with open("palettes.svh", "w") as f:
        f.write("// Auto-generated by contour_golden.py - preset palettes for palette_loader.\n")
        for name, pal in palettes:
            entries = ", ".join(f"24'h{r:02X}{g:02X}{b:02X}" for r,g,b in pal)
            f.write(f"localparam logic [23:0] {name} [16] = '{{ {entries} }};\n")

def main():
    mem = make_heightmap()
    with open("heightmap.hex","w") as f:
        for w in mem: f.write(f"{w:04x}\n")
    write_golden("golden_p0.txt", mem, P0)
    write_golden("golden_p1.txt", mem, P1)
    emit_svh([("PAL_P0",P0),("PAL_P1",P1),("PAL_P2",P2)])
    print("wrote heightmap.hex, golden_p0.txt, golden_p1.txt, palettes.svh")
    print("P1 cividis[0,8,15] =", P1[0], P1[8], P1[15])

if __name__ == "__main__":
    main()
